### ISSUE TITLE
Why are numy and scipy are required during installation?

### ISSUE THREAD

**Issue by andreArtelt** [MrNuggelz/sklearn-lvq#12]
Hi,

I am wondering why numy and scipy are required during installation. Is it really necessary?

The problem is that when I have a ''blank system'' (i.e. no python packages are installed) and install a package that requires sklearn-lvq, the installation fails because numpy and scipy have not been installed yet - they would be installed afterwards but not necessarily before sklearn-lvq. 

If possible, please stop requiring numpy and scipy during installation and create a new release on PyPI.

Best wishes,
André

**Comment by theblackfly** [comment]
The following code in `setup.py` is the culprit.
```python
try:
    import numpy
except ImportError:
    print('numpy is required during installation')
    sys.exit(1)

try:
    import scipy
except ImportError:
    print('scipy is required during installation')
    sys.exit(1)
```

**Comment by andreArtelt** [comment]
I see.
But to me this code looks useless - it does not seem to do anything meaningful. So why is it included?

**Comment by theblackfly** [comment]
I don't know why the author included it. It seems like those lines can be safely removed and added instead to `requirements.txt` as dependencies.

**Comment by theblackfly** [comment]
I fixed the issue. Refer PR<https://github.com/MrNuggelz/sklearn-lvq/pull/13>.

**Comment by andreArtelt** [comment]
Great work @theblackfly :+1: 
I hope that the author will merge your pull request soon and create a new release - otherwise, people will continue running into this issue when installing sklearn-lvq via pip :/

**Comment by theblackfly** [comment]
It has been pulled. This issue can now be closed.
