### ISSUE TITLE
'GmlvqModel' object has no attribute 'decision_function'

### ISSUE THREAD

**Issue by Ariadnaaz** [MrNuggelz/sklearn-lvq#17]
In the documentation, I've seen that one of the methods available for the GmlvqModel is decision_function(x). But when I try to use it, I get the error "AttributeError: 'GmlvqModel' object has no attribute 'decision_function'". Do you know how to fix this?

**Comment by MrNuggelz** [comment]
I can not reproduce your problem. This code works on my machine:
```
from sklearn_lvq import GmlvqModel
GmlvqModel().decision_function()
```
Could you show a code sample where this error occurs?

**Comment by Ariadnaaz** [comment]
Sorry, it seems to be working fine now somehow, although I had tried many times. Thank you for the fast reply anyways!
